---
environment: development
chdir: .
address: 127.0.0.1
port: 18001
rackup: config.ru
pid: run/server.pid
log: run/server.log
max_conns: 128
timeout: 30
max_persistent_conns: 16
servers: 1
daemonize: true
