source 'https://rubygems.org'
gem 'SystemTimer', platforms: :ruby_18
gem 'eventmachine'
gem 'hiredis'
gem 'redis', '>= 2.2.0', require: ['redis', 'redis/connection/hiredis']
gem 'redis-objects'
gem 'sinatra', git: 'git://github.com/sinatra/sinatra.git'
gem 'haml'
gem 'haml-contrib'
gem 'erubis'
gem 'maruku'
gem 'sass'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'builder'
gem 'pg'
gem 'sqlite3'
gem 'json'
gem 'rack', '~> 1.5', git: 'git://github.com/rack/rack.git', tag: '1.5.5'
gem 'rake'
gem 'sinatra-flash', require: 'sinatra/flash'
gem 'sinatra-redirect-with-flash', require: 'sinatra/redirect_with_flash'
gem 'bcrypt'
gem 'activesupport'
gem 'uuidtools'
gem 'hipchat'
gem 'will_paginate'
gem 'omniauth', '~> 1.0.3'
gem 'omniauth-google-apps'
gem 'oa-openid'
gem 'openid-redis-store', require: 'openid_redis_store'
gem 'yajl-ruby'
gem 'sinatra-static-assets', require: 'sinatra/static_assets'
gem 'rack-session-redis', git: 'git://github.com/vangberg/rack-session-redis.git', require: 'rack/session/redis'
gem 'unicorn'
gem 'addressable'
gem 'sentry-raven', git: 'https://github.com/getsentry/raven-ruby.git'

group :development do
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-rbenv-install'
  gem 'rack-mini-profiler', require: 'rack-mini-profiler'
end

group :test do
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'rack-test', require: 'rack/test'
end
